import type { Metadata } from "next";
import { EB_Garamond, Jost } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin", "latin-ext"]
})

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin", "latin-ext"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${ebGaramond.variable} ${jost.variable} antialiased`}
    >
      <body>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
